name: "get environment"
description: "Returns the environment name that the caller workflow should use."
inputs:
  ref:
    description: "The reference (github.ref)."
    required: false
    default: ${{ github.ref }}

runs:
  using: composite
  steps:
    - name: Get environment
      id: getenv
      run: |
        if [[ ${{ inputs.ref }} == "refs/heads/master" ]]; then
          echo "::set-output name=environmentname::production"
          echo "Returned production environment!"
        fi
        if [[ ${{ inputs.ref }} == "refs/heads/dev" ]]; then
          echo "::set-output name=environmentname::development"
          echo "Returned development environment!"
        fi
        if [[ ${{ inputs.ref }} == "refs/heads/staging" ]]; then
          echo "::set-output name=environmentname::staging"
          echo "Returned staging environment!"
        fi
      shell: bash

outputs:
  environmentname:
    description: "The environment name."
    value: ${{ steps.getenv.outputs.environmentname }}
